vk-399-api-stability: base cache restoring check fixed, added commands for tag caching

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,6 +11,16 @@ commands:
           paths:
             - api_logs
 
+  save-api-diff-cache-by-tag:
+    parameters:
+      api_diff_cache:
+        type: string
+    steps:
+      - save_cache:
+          key: nav-api-diff-cache-v5-{{ .Environment.CIRCLE_WORKFLOW_ID }}-<< parameters.api_diff_cache >>
+          paths:
+            - api_logs
+
   restore-api-diff-cache:
     parameters:
         api_diff_cache:
@@ -19,6 +29,15 @@ commands:
       - restore_cache:
           keys:
             - nav-api-diff-cache-v5-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ << parameters.api_diff_cache >> }}
+
+  restore-api-diff-cache-by-tag:
+    parameters:
+        api_diff_cache:
+          type: string
+    steps:
+      - restore_cache:
+          keys:
+            - nav-api-diff-cache-v5-{{ .Environment.CIRCLE_WORKFLOW_ID }}-<< parameters.api_diff_cache >>
 
   build-api-diff-report:
     steps:
@@ -321,15 +340,12 @@ jobs:
           name: Move Api Diff
           command: |
             mv api_logs original_api
-      - restore-api-diff-cache:
+      - restore-api-diff-cache-by-tag:
           api_diff_cache: << parameters.base_api_tag >>
       - run:
           name: Verify Base API report exists
           command: |
-            if test -f "$CIRCLE_WORKING_DIRECTORY/api_logs"; then \
-              echo "Base API log file exists" \
-              export API_CACHE_EXISTS=TRUE \
-            fi
+            test -e "$CIRCLE_WORKING_DIRECTORY/api_logs" && echo "Base API log file exists" && export API_CACHE_EXISTS=TRUE || echo Base API log not found
       - unless:
           condition: .Environment.API_CACHE_EXISTS
           steps:
@@ -343,7 +359,7 @@ jobs:
                 name: Install prerequisites
                 command: if [ $(xcversion simulators | grep -cF "iOS << parameters.iOS >> Simulator (installed)") -eq 0 ]; then xcversion simulators --install="iOS << parameters.iOS >>" || true; fi
             - *save-cache
-            - save-api-diff-cache:
+            - save-api-diff-cache-by-tag:
                 api_diff_cache: << parameters.base_api_tag >>
       - run:
           name: Restore latest APIDiffReport
